#![deny(rustdoc::broken_intra_doc_links)]

//! Core types for working with voxels.

mod b_vox_effective_property;
mod b_vox_hierarchy_node;
mod b_vox_layer;
mod b_vox_material;
mod b_vox_object;
mod b_vox_palette;
mod b_vox_property;
mod b_vox_value_pool;
mod b_vox_value_pool_value;
mod b_vox_voxel;
mod error;
mod result;
mod vox_effective_palette;
mod vox_effective_property;
mod vox_gc_remap;
mod vox_hierarchy_node;
mod vox_liveness;
mod vox_main;
mod vox_map;
mod vox_object;
mod vox_palette;
mod vox_property;
mod vox_runtime_state;
mod vox_value;
mod vox_value_pool;
mod vox_value_pool_flaw;
mod vox_value_pool_kind;
mod vox_value_pool_value_ref;

pub use b_vox_effective_property::*;
pub use b_vox_hierarchy_node::*;
pub use b_vox_layer::*;
pub use b_vox_material::*;
pub use b_vox_object::*;
pub use b_vox_palette::*;
pub use b_vox_property::*;
pub use b_vox_value_pool::*;
pub use b_vox_value_pool_value::*;
pub use b_vox_voxel::*;
pub use error::*;
pub use result::*;
pub use vox_effective_palette::*;
pub use vox_effective_property::*;
pub use vox_gc_remap::*;
pub use vox_hierarchy_node::*;
pub use vox_liveness::*;
pub use vox_main::*;
pub use vox_map::*;
pub use vox_object::*;
pub use vox_palette::*;
pub use vox_property::*;
pub use vox_runtime_state::*;
pub use vox_value::*;
pub use vox_value_pool::*;
pub(crate) use vox_value_pool_flaw::*;
pub use vox_value_pool_kind::*;
pub use vox_value_pool_value_ref::*;
