[workspace]

members = [
    "projects/tyt/tyt-claude",
    "projects/tyt/tyt-common",
    "projects/tyt/tyt-cubemap",
    "projects/tyt/tyt-fbx",
    "projects/tyt/tyt-fs",
    "projects/tyt/tyt-image",
    "projects/tyt/tyt-injection",
    "projects/tyt/tyt-material",
    "projects/tyt/tyt-meshy",
    "projects/tyt/tyt-meta",
    "projects/tyt/tyt-oai",
    "projects/tyt/tyt-preferences",
    "projects/tyt/tyt-vmax",
    "projects/tyt/tyt",
    "projects/utilities/ty-math-serde",
    "projects/utilities/ty-math",
    "projects/utilities/voxcore",
    "projects/utilities/voxl",
    "projects/utilities/voxsmith",
    "projects/voxel-codecs/goxl-codec",
    "projects/voxel-codecs/goxl",
    "projects/voxel-codecs/mvox-codec",
    "projects/voxel-codecs/mvox",
    "projects/voxel-codecs/qbcl-codec",
    "projects/voxel-codecs/qbcl",
    "projects/voxel-codecs/vmax-codec",
    "projects/voxel-codecs/vmax",
    "projects/voxel-codecs/voxj-codec",
    "projects/voxel-codecs/voxj",
]

resolver = "2"

[patch.crates-io]

tyt = { path = "projects/tyt/tyt" }
tyt-claude = { path = "projects/tyt/tyt-claude" }
tyt-common = { path = "projects/tyt/tyt-common" }
tyt-cubemap = { path = "projects/tyt/tyt-cubemap" }
tyt-fbx = { path = "projects/tyt/tyt-fbx" }
tyt-fs = { path = "projects/tyt/tyt-fs" }
tyt-image = { path = "projects/tyt/tyt-image" }
tyt-injection = { path = "projects/tyt/tyt-injection" }
tyt-material = { path = "projects/tyt/tyt-material" }
tyt-meshy = { path = "projects/tyt/tyt-meshy" }
tyt-meta = { path = "projects/tyt/tyt-meta" }
tyt-oai = { path = "projects/tyt/tyt-oai" }
tyt-preferences = { path = "projects/tyt/tyt-preferences" }
tyt-vmax = { path = "projects/tyt/tyt-vmax" }

ty-math = { path = "projects/utilities/ty-math" }
ty-math-serde = { path = "projects/utilities/ty-math-serde" }
voxcore = { path = "projects/utilities/voxcore" }
voxl = { path = "projects/utilities/voxl" }
voxsmith = { path = "projects/utilities/voxsmith" }

voxj = { path = "projects/voxel-codecs/voxj" }
voxj-codec = { path = "projects/voxel-codecs/voxj-codec" }
vmax = { path = "projects/voxel-codecs/vmax" }
vmax-codec = { path = "projects/voxel-codecs/vmax-codec" }
mvox = { path = "projects/voxel-codecs/mvox" }
mvox-codec = { path = "projects/voxel-codecs/mvox-codec" }
goxl = { path = "projects/voxel-codecs/goxl" }
goxl-codec = { path = "projects/voxel-codecs/goxl-codec" }
qbcl = { path = "projects/voxel-codecs/qbcl" }
qbcl-codec = { path = "projects/voxel-codecs/qbcl-codec" }
