[workspace]
members = [
    "projects/ty-math-serde",
    "projects/ty-math",
    "projects/tyt-claude",
    "projects/tyt-common",
    "projects/tyt-cubemap",
    "projects/tyt-fbx",
    "projects/tyt-fs",
    "projects/tyt-image",
    "projects/tyt-injection",
    "projects/tyt-material",
    "projects/tyt-meshy",
    "projects/tyt-meta",
    "projects/tyt-oai",
    "projects/tyt-preferences",
    "projects/tyt",
    "projects/tyt-vmax",
    "projects/voxcore",
    "projects/voxj-codec",
    "projects/voxj",
    "projects/voxsmith",
    "projects/vmax-codec",
    "projects/vmax",
    "projects/mvox-codec",
    "projects/mvox",
]
resolver = "2"

[patch.crates-io]
ty-math = { path = "projects/ty-math" }
ty-math-serde = { path = "projects/ty-math-serde" }
tyt = { path = "projects/tyt" }
tyt-claude = { path = "projects/tyt-claude" }
tyt-common = { path = "projects/tyt-common" }
tyt-cubemap = { path = "projects/tyt-cubemap" }
tyt-fbx = { path = "projects/tyt-fbx" }
tyt-fs = { path = "projects/tyt-fs" }
tyt-image = { path = "projects/tyt-image" }
tyt-injection = { path = "projects/tyt-injection" }
tyt-material = { path = "projects/tyt-material" }
tyt-meshy = { path = "projects/tyt-meshy" }
tyt-meta = { path = "projects/tyt-meta" }
tyt-oai = { path = "projects/tyt-oai" }
tyt-preferences = { path = "projects/tyt-preferences" }
tyt-vmax = { path = "projects/tyt-vmax" }
voxcore = { path = "projects/voxcore" }
voxj = { path = "projects/voxj" }
voxj-codec = { path = "projects/voxj-codec" }
voxsmith = { path = "projects/voxsmith" }
vmax = { path = "projects/vmax" }
vmax-codec = { path = "projects/vmax-codec" }
mvox = { path = "projects/mvox" }
mvox-codec = { path = "projects/mvox-codec" }
