[package]
name = "vmax-codec"
version = "0.1.6"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Parses Voxel Max binary payloads (.vmaxb / .vmaxpsb) into vmax types."

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
vmax = { version = "0.1.0" }
