[package]
name = "vox-value-language"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "A typed expression language over per-swatch, per-voxel, per-face, and per-corner values."

[package.metadata.workspaces]
independent = true

[dependencies]
branded-id = "0.1.10"
