[package]
name = "tyt-fbx"
version = "0.1.7"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Command-line tools for working with FBX files."
autobins = false

[[bin]]
name = "fbx"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
branded-id = "0.1.7"
clap = { version = "4.5.58", features = ["derive"] }
clap_complete = { version = "4.5", optional = true }
treegrid = { version = "0.1.0", default-features = false, features = [
    "render_hierarchy",
] }
treeselect = "0.1.0"
tyt-common = { version = "0.1.0" }
ty-math = { version = "0.1.0" }
tyt-injection = { version = "0.1.0", optional = true }

[features]
default = ["impl"]
impl = ["dep:tyt-injection"]
bin = ["impl", "dep:clap_complete"]
