[package]
name = "vxl"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "A command-line tool for working with voxels."
autobins = false

[[bin]]
name = "vxl"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
clap_complete = { version = "4.5", optional = true }
vmax-codec = { version = "0.1.0", optional = true }
voxcore = { version = "0.1.0", optional = true }
voxj-codec = { version = "0.1.0", optional = true }
voxsmith = { version = "0.1.0", optional = true }

[features]
default = ["impl"]
impl = [
    "dep:vmax-codec",
    "dep:voxcore",
    "dep:voxj-codec",
    "dep:voxsmith",
]
bin = ["impl", "dep:clap_complete"]
