[package]
name = "vxl"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "A command-line tool for working with voxels."
autobins = false

[[bin]]
name = "vxl"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
clap_complete = { version = "4.5", optional = true }
libc = { version = "0.2", optional = true }
voxcore = { version = "0.2.1", default-features = false }
voxsmith = { version = "0.2.0", features = ["gltf", "report"] }

[features]
default = ["impl"]
impl = ["dep:libc"]
bin = ["impl", "dep:clap_complete"]
