[package]
name = "vxl"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "A command-line tool for working with voxels."
autobins = false

[[bin]]
name = "vxl"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
branded-id = { version = "0.1.3", optional = true }
clap = { version = "4.5.58", features = ["derive"] }
clap_complete = { version = "4.5", optional = true }
libc = { version = "0.2", optional = true }
pathspec = { version = "0.1.0", optional = true }
serde_json = { version = "1", features = ["preserve_order"], optional = true }
treegrid = { version = "0.1.0", features = ["json", "ty-math"], optional = true }
ty-math = { version = "0.1.7", optional = true }
vmax-codec = { version = "0.1.0", optional = true }
voxcore = { version = "0.1.0", optional = true }
voxj-codec = { version = "0.1.0", optional = true }
voxsmith = { version = "0.1.0", optional = true }

[dev-dependencies]
ty-math = "0.1.7"

[features]
default = ["impl"]
impl = [
    "dep:branded-id",
    "dep:libc",
    "dep:pathspec",
    "dep:serde_json",
    "dep:treegrid",
    "dep:ty-math",
    "dep:vmax-codec",
    "dep:voxcore",
    "dep:voxj-codec",
    "dep:voxsmith",
    "voxsmith/gltf",
]
bin = ["impl", "dep:clap_complete"]
