[package]
name = "vmax-codec"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Reads and writes Voxel Max (.vmax) package files."
keywords = ["voxelmax", "vmax", "voxel", "3d", "codec"]
categories = ["parser-implementations", "encoding", "game-development", "graphics"]

[dependencies]
lzfse = { version = "0.2", optional = true }
plist = { version = "1", optional = true }
png = { version = "0.18", optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", features = [
    "float_roundtrip",
    "preserve_order",
], optional = true }
vmax = { version = "0.1.8", default-features = false }

[features]
default = ["impl"]
impl = [
    "dep:lzfse",
    "dep:plist",
    "dep:png",
    "dep:serde",
    "dep:serde_json",
    "vmax/serde",
]
