[package]
name = "mvox-codec"
version = "0.1.1"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Reads and writes MagicaVoxel (.vox) files."
keywords = ["magicavoxel", "vox", "voxel", "3d", "codec"]
categories = ["parser-implementations", "encoding", "game-development", "graphics"]

[dependencies]
mvox = "0.1.0"
