[package]
name = "goxl-voxcore"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Converts between Goxel files and the voxcore state."
keywords = ["goxel", "gox", "voxel", "3d", "conversion"]
categories = ["encoding", "game-development", "graphics"]

[dependencies]
branded-id = "0.1.7"
goxl = "0.1.0"
goxl-codec = { version = "0.1.0", default-features = false, optional = true }
serde = { version = "1", features = ["derive"], optional = true }
ty-math = { version = "0.2.0", default-features = false, features = ["color"] }
voxcore = { version = "0.2.1", default-features = false, features = ["color"] }

[dev-dependencies]
goxl-codec = { version = "0.1.0", features = ["impl"] }

[features]
default = ["codec", "ext"]
codec = ["dep:goxl-codec"]
ext = ["dep:serde", "voxcore/json"]
impl = ["goxl-codec?/impl"]
