[package]
name = "voxconv"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Reads and writes voxel file formats through the voxcore state."
keywords = ["voxel", "conversion", "3d", "vox", "voxj"]
categories = ["encoding", "game-development", "graphics"]

[dependencies]
goxl-voxcore = { version = "0.1.0", default-features = false, optional = true }
mvox-voxcore = { version = "0.1.0", default-features = false, optional = true }
qbcl-voxcore = { version = "0.1.0", default-features = false, optional = true }
vmax = { version = "0.1.8", default-features = false, optional = true }
vmax-voxcore = { version = "0.1.0", default-features = false, optional = true }
voxcore = { version = "0.2.1", default-features = false }
voxj = { version = "0.1.3", default-features = false, optional = true }
voxj-voxcore = { version = "0.2.0", default-features = false, optional = true }

[dev-dependencies]
branded-id = "0.1.7"
ty-math = { version = "0.2.0", default-features = false }

[features]
default = ["codec", "ext", "goxl", "impl", "mvox", "qbcl", "vmax", "voxj"]

goxl = ["dep:goxl-voxcore", "_format"]
mvox = ["dep:mvox-voxcore", "_format"]
qbcl = ["dep:qbcl-voxcore", "_format"]
vmax = ["dep:vmax", "dep:vmax-voxcore", "_format"]
voxj = ["dep:voxj", "dep:voxj-voxcore", "_format"]

ext = [
    "goxl-voxcore?/ext",
    "mvox-voxcore?/ext",
    "qbcl-voxcore?/ext",
    "vmax-voxcore?/ext",
]

codec = [
    "ext",
    "goxl-voxcore?/codec",
    "mvox-voxcore?/codec",
    "qbcl-voxcore?/codec",
    "vmax-voxcore?/codec",
    "voxj-voxcore?/codec",
]

impl = [
    "codec",
    "goxl-voxcore?/impl",
    "qbcl-voxcore?/impl",
    "vmax-voxcore?/impl",
    "voxj-voxcore?/impl",
]

_format = []
