[package]
name = "voxj-codec"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Encodes voxj types into .voxj / .voxjz documents."
keywords = ["voxel", "voxj", "json", "3d", "codec"]
categories = [
    "encoding",
    "game-development",
    "graphics",
    "parser-implementations",
]

[dependencies]
flate2 = { version = "1", optional = true }
serde_json = { version = "1", features = [
    "float_roundtrip",
    "preserve_order",
], optional = true }
voxj = { version = "0.1.3", default-features = false }

[features]
default = ["impl"]
impl = ["dep:flate2", "dep:serde_json", "voxj/impl"]
