[package]
name = "voxsmith"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Utilities for working with voxels."

[dependencies]
branded-id = "0.1"
ty-math = { version = "0.1.0" }
voxcore = { version = "0.1.0" }
voxj = { version = "0.1.0" }
voxj-codec = { version = "0.1.0" }
