[package]
name = "voxsmith"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Utilities for working with voxels."

[dependencies]
branded-id = "0.1.3"
mvox = "0.1.0"
mvox-codec = "0.1.0"
serde = { version = "1", features = ["derive"] }
ty-math = "0.1.7"
vmax = { version = "0.1.7", features = ["serde"] }
voxcore = "0.1.0"
voxj = { version = "0.1.1", features = ["serde"] }
voxj-codec = "0.1.1"
