[package]
name = "goxl"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Core data types for the Goxel (.gox) file format."
keywords = ["goxel", "gox", "voxel", "3d", "model"]
categories = ["data-structures", "game-development", "graphics"]

[dependencies]
