use crate::Role;

/// A single turn in a stored conversation.
///
/// User turns carry only a [`Role`] and `content`. Assistant turns additionally
/// carry the `image` they generated (omitted when `--no-gen` was used) and the
/// `responseId` that lets the next request continue from this point.
#[derive(Clone, Debug)]
#[cfg_attr(feature = "impl", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "impl", serde(rename_all = "camelCase"))]
pub struct Turn {
    /// Who authored the turn.
    pub role: Role,

    /// The text content of the turn.
    pub content: String,

    /// The file name of the image generated by an assistant turn, relative to
    /// the conversation directory.
    #[cfg_attr(
        feature = "impl",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub image: Option<String>,

    /// The OpenAI server-side response id of an assistant turn.
    #[cfg_attr(
        feature = "impl",
        serde(default, skip_serializing_if = "Option::is_none")
    )]
    pub response_id: Option<String>,
}
