[package]
name = "tyt-preferences"
version = "0.1.6"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Layered preference loading from sectioned config files."

[dependencies]
jsonc-parser = { version = "0.33.1", features = ["cst", "serde"], optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", features = ["preserve_order"], optional = true }

[features]
default = ["impl", "impl-jsonc"]
impl = []
impl-json = ["dep:serde", "dep:serde_json"]
impl-jsonc = ["dep:serde", "dep:serde_json", "dep:jsonc-parser"]
