[package]
name = "voxsmith"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Utilities for working with voxels."

[dependencies]
branded-id = "0.1.7"
meshdoc = "0.1.0"
pathspec = "0.2.0"
png = { version = "0.18.1", optional = true }
serde_json = { version = "1", optional = true }
treegrid = { version = "0.2.0", features = [
    "json",
    "ty-math",
], optional = true }
treeselect = { version = "0.1.1", optional = true }
ty-math = "0.2.0"
voxcore = { version = "0.2.1", default-features = false, features = ["color"] }
zune-jpeg = { version = "0.5", optional = true }

[features]
default = [
    "hierarchy_show",
    "impl",
    "info",
    "mesh",
    "palette_list",
    "palette_show",
    "to",
    "validate",
    "voxelize",
]

hierarchy_show = ["_treegrid", "dep:treeselect"]
info = ["_treegrid"]
mesh = []
palette_list = ["_treegrid"]
palette_show = ["_treegrid", "dep:serde_json"]
to = []
validate = ["_treegrid"]
voxelize = []

impl = ["dep:png", "dep:zune-jpeg"]

_treegrid = ["dep:treegrid"]

[dev-dependencies]
png = "0.18"
