[package]
name = "vmax-voxcore"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Converts between Voxel Max packages and the voxcore state."
keywords = ["voxelmax", "vmax", "voxel", "3d", "conversion"]
categories = ["encoding", "game-development", "graphics"]

[dependencies]
branded-id = "0.1.7"
serde = { version = "1", features = ["derive"], optional = true }
ty-math = "0.2.0"
vmax = { version = "0.1.8", default-features = false }
vmax-codec = { version = "0.2.0", default-features = false, optional = true }
voxcore = { version = "0.2.1", default-features = false, features = ["color"] }

[dev-dependencies]
vmax-codec = { version = "0.2.0", features = ["impl"] }

[features]
default = ["codec", "ext"]
codec = ["dep:vmax-codec"]
ext = ["dep:serde", "voxcore/json", "vmax/serde"]
impl = ["vmax-codec?/impl"]
